from django.urls import path

from .views import (
    AcceptMatchView,
    AnalyzeDonationView,
    BecomeReceiverView,
    ClaimOrganizationView,
    CreateNeedView,
    DeclineMatchView,
    DeliverMatchView,
    DonationMatchesView,
    ExtractDonationView,
    LoginView,
    MeView,
    MyDonationsView,
    MyOrganizationMatchesView,
    MyOrganizationView,
    NeedDetailView,
    NotificationListView,
    NotificationReadAllView,
    NotificationReadView,
    OrganizationDetailView,
    OrganizationListView,
    PledgeMatchView,
    RefreshView,
    RegisterView,
    StatsView,
)

urlpatterns = [
    path("stats/", StatsView.as_view()),
    path("auth/register/", RegisterView.as_view()),
    path("auth/login/", LoginView.as_view()),
    path("auth/refresh/", RefreshView.as_view()),
    path("auth/me/", MeView.as_view()),
    path("auth/become-receiver/", BecomeReceiverView.as_view()),
    path("organizations/", OrganizationListView.as_view()),
    path("organizations/me/", MyOrganizationView.as_view()),
    path("organizations/me/matches/", MyOrganizationMatchesView.as_view()),
    path("organizations/<int:pk>/", OrganizationDetailView.as_view()),
    path("organizations/<int:pk>/needs/", CreateNeedView.as_view()),
    path("organizations/<int:pk>/claim/", ClaimOrganizationView.as_view()),
    path("needs/<int:pk>/", NeedDetailView.as_view()),
    path("donations/extract/", ExtractDonationView.as_view()),
    path("donations/analyze/", AnalyzeDonationView.as_view()),
    path("donations/mine/", MyDonationsView.as_view()),
    path("donations/<int:pk>/matches/", DonationMatchesView.as_view()),
    path("matches/<int:pk>/pledge/", PledgeMatchView.as_view()),
    path("matches/<int:pk>/accept/", AcceptMatchView.as_view()),
    path("matches/<int:pk>/decline/", DeclineMatchView.as_view()),
    path("matches/<int:pk>/deliver/", DeliverMatchView.as_view()),
    path("notifications/", NotificationListView.as_view()),
    path("notifications/read-all/", NotificationReadAllView.as_view()),
    path("notifications/<int:pk>/read/", NotificationReadView.as_view()),
]
