# Generated by Django 5.2.17 on 2026-08-29 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pledged', 'Pledged'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('delivered', 'Delivered')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('suggested', 'Suggested'), ('pledged', 'Pledged'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('delivered', 'Delivered')], default='suggested', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
