# Generated by Django 5.2.17 on 2026-08-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_match_loop'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_change_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
